### ISSUE TITLE
Audio format unrecognized

### ISSUE THREAD

**Issue by venkat-sf** [seanghay/uvr#5]
Hi. I'm trying to run this code on Amazon Linux with Python 3.10 and get the below error. I don't think there's any problem with the audio file. It seems to do with incompatibility between Python and module versions. Any ideas for a fix?

```
$ python separate.py 
Traceback (most recent call last):
  File "/home/ssm-user/uvr/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "/home/ssm-user/uvr/venv/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/ssm-user/uvr/venv/lib/python3.10/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'audio.aac': Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ssm-user/uvr/separate.py", line 109, in <module>
    pre_fun._path_audio_(audio_path , save_path,save_path)
  File "/home/ssm-user/uvr/separate.py", line 59, in _path_audio_
    X_wave[d], _ = librosa.core.load(
  File "/home/ssm-user/uvr/venv/lib/python3.10/site-packages/librosa/util/decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "/home/ssm-user/uvr/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/home/ssm-user/uvr/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/home/ssm-user/uvr/venv/lib/python3.10/site-packages/audioread/__init__.py", line 132, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
```

**Comment by seanghay** [comment]
You should install `libsndfile1` via `apt install libsndfile1 --yes` and `ffmpeg`

Alternatively, you can transcode the `aac` audio to `wav` file format by running the command:

```shell
ffmpeg -i audio.aac audio.wav
```

**Comment by venkat-sf** [comment]
@seanghay

Was able to install _libsndfile_ and _ffmpeg_ and get it to work! Thank you!

Maybe, we should add it to the Readme?

**Comment by seanghay** [comment]
> @seanghay
> 
> Was able to install _libsndfile_ and _ffmpeg_ and get it to work! Thank you!
> 
> Maybe, we should add it to the Readme?
> 

Please help to open a pull request

**Comment by venkat-sf** [comment]
[Done](https://github.com/seanghay/uvr/pull/6)
