### ISSUE TITLE
How do I add a demucs model?

### ISSUE THREAD

**Issue by nickamx** [seanghay/uvr#7]
I'm trying to add UVR_Demucs_Model_1 model, as it works better and faster for my tasks. I added UVR_Demucs_Model_1.yaml and ebf34a2db.th to uvr5_weights.
changed the code to model_path='uvr5_weights/UVR_Demucs_Model_1.yaml' but I can't run the model.

I get an error:
Traceback (most recent call last):
  File "C:\Users\Admin/Documents\uvr auto test\uvr-main\uvr-main\separate.py", line 105, in <module>
    pre_fun = _audio_pre_(model_path=model_path,device=device,is_half=is_half)
  File "C:\Users\Admin/Documents\uvr auto test\uvr-main\uvr-main\separate.py", line 35, in __init__
    param_name , model_params_d = _get_name_params(model_path , model_hash)
  File "C:\Users\Admin/Documents\uvr auto test\uvr-main\uvr-main\uvr5_pack\utils.py", line 242, in _get_name_params
    return param_name_auto , model_params_auto
UnboundLocalError: local variable 'param_name_auto' referenced before assignment

I am a newbie and if you can help me, it would be very much appreciated.

**Comment by seanghay** [comment]
I don't know about that too. I think you should try using https://pypi.org/project/demucs/ instead it's easier to install.

Read more: https://seanghay.com/posts/audio-source-sep

**Comment by nickamx** [comment]
Thank you!
